"""Factories for the visual editor's slide-element JSON model.

This is the ONLY place the element schema is written by hand on the backend.
It mirrors, field for field, the TypeScript model in
frontend/src/routes/dashboard.courses_.$courseId_.editor.$moduleId.tsx —
anything produced here lands in course_lessons.slides (jsonb) and is then a
normal, hand-editable element on the canvas. Nothing generated by these
factories is special-cased, locked, or flattened: a title, a decorative dot
grid and a footer page number are all the same kind of object the teacher
gets when they click "Texte" or "Rectangle" themselves. That is what makes
"the teacher can modify literally anything in the template" true by
construction rather than by a per-feature escape hatch.

Design space is a fixed 800x450 (16:9); the editor and the student viewer
both scale that same space, so coordinates here are resolution-independent.
"""
import uuid

STAGE_W = 800
STAGE_H = 450

DEFAULT_FONT = "Manrope, sans-serif"
DEFAULT_INK = "#1C2331"


def uid() -> str:
    return str(uuid.uuid4())


def text(
    x: float, y: float, w: float, h: float, content: str, *,
    size: float = 11, bold: bool = False, italic: bool = False, underline: bool = False,
    align: str = "left", color: str = DEFAULT_INK, background: str | None = None,
    font: str = DEFAULT_FONT, rotation: float = 0,
) -> dict:
    return {
        "id": uid(), "type": "text", "x": x, "y": y, "width": w, "height": h, "rotation": rotation,
        "content": content, "fontSize": size, "fontFamily": font,
        "bold": bold, "italic": italic, "underline": underline,
        "align": align, "color": color, "backgroundColor": background,
    }


def _shape(shape_type: str, x, y, w, h, *, fill, stroke, stroke_width, radius, opacity, rotation) -> dict:
    return {
        "id": uid(), "type": "shape", "shapeType": shape_type,
        "x": x, "y": y, "width": w, "height": h, "rotation": rotation,
        "fill": fill, "stroke": stroke, "strokeWidth": stroke_width,
        "cornerRadius": radius, "opacity": opacity,
    }


def rect(
    x: float, y: float, w: float, h: float, *,
    fill: str = "#FFFFFF", stroke: str = "transparent", stroke_width: float = 0,
    radius: float = 0, opacity: float = 1, rotation: float = 0,
) -> dict:
    return _shape("rectangle", x, y, w, h, fill=fill, stroke=stroke, stroke_width=stroke_width,
                  radius=radius, opacity=opacity, rotation=rotation)


def circle(
    x: float, y: float, w: float, h: float, *,
    fill: str = "#FFFFFF", stroke: str = "transparent", stroke_width: float = 0,
    opacity: float = 1, rotation: float = 0,
) -> dict:
    """x/y/w/h is the bounding box, matching every other element — the editor
    converts to Konva's centre-anchored Ellipse at the render boundary only."""
    return _shape("circle", x, y, w, h, fill=fill, stroke=stroke, stroke_width=stroke_width,
                  radius=0, opacity=opacity, rotation=rotation)


def line(x: float, y: float, dx: float, dy: float, *, stroke: str, stroke_width: float = 1, opacity: float = 1) -> dict:
    """A line runs from (x, y) to (x + dx, y + dy) — width/height carry the
    delta, which is how the editor already stores its own line elements."""
    return _shape("line", x, y, dx, dy, fill="transparent", stroke=stroke, stroke_width=stroke_width,
                  radius=0, opacity=opacity, rotation=0)


def image(x: float, y: float, w: float, h: float, src: str, *, opacity: float = 1, rotation: float = 0) -> dict:
    return {
        "id": uid(), "type": "image", "x": x, "y": y, "width": w, "height": h,
        "rotation": rotation, "src": src, "opacity": opacity,
    }


def motif(
    x: float, y: float, w: float, h: float, *,
    color: str, dot: float = 3, gap: float = 14, opacity: float = 1, rotation: float = 0,
) -> dict:
    """A repeating dot grid as ONE element.

    The M101 cover tiles a corner with ~150 dots. Emitting those as 150
    circles would technically be "editable" while being unusable — the
    teacher would have to select and nudge each one, and every deck would
    carry hundreds of throwaway objects. As a single element with editable
    colour/size/spacing, recolouring or resizing the whole trame is one
    interaction and the deck stays small.
    """
    return {
        "id": uid(), "type": "motif", "x": x, "y": y, "width": w, "height": h, "rotation": rotation,
        "motifType": "dots", "color": color, "dotSize": dot, "gap": gap, "opacity": opacity,
    }


def visual(
    x: float, y: float, w: float, h: float, *,
    label: str = "Emplacement visuel", src: str | None = None,
    fill: str = "#F5F7F4", stroke: str = "#C9CFC7", caption_color: str = "#9AA79B",
) -> list[dict]:
    """An image zone. Filled with the chapter's own uploaded illustration when
    there is one, otherwise a labelled frame the teacher drops an image into.
    Returns a list because the empty state is two elements (frame + caption),
    and callers splat it either way so they never branch on which it was."""
    if src:
        return [image(x, y, w, h, src)]
    return [
        rect(x, y, w, h, fill=fill, stroke=stroke, stroke_width=1, radius=3),
        text(x, y + h / 2 - 9, w, 18, label, size=9, italic=True, align="center", color=caption_color),
    ]


def slide(title: str, elements: list[dict], *, background: str | None = None) -> dict:
    return {"id": uid(), "title": title, "elements": elements, "background": background}
