/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as PlateformeRouteImport } from './routes/plateforme'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApproveLoginRouteImport } from './routes/approve-login'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardTimetablesRouteImport } from './routes/dashboard.timetables'
import { Route as DashboardTeachingSessionsRouteImport } from './routes/dashboard.teaching-sessions'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardSchedulesRouteImport } from './routes/dashboard.schedules'
import { Route as DashboardRhRouteImport } from './routes/dashboard.rh'
import { Route as DashboardReunionsInstancesRouteImport } from './routes/dashboard.reunions-instances'
import { Route as DashboardPurchaseRequestsRouteImport } from './routes/dashboard.purchase-requests'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard.performance'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMeetingsRouteImport } from './routes/dashboard.meetings'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard.library'
import { Route as DashboardExamsRouteImport } from './routes/dashboard.exams'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardCommunicationRouteImport } from './routes/dashboard.communication'
import { Route as DashboardClassesRouteImport } from './routes/dashboard.classes'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard.assignments'
import { Route as DashboardArchitectureRouteImport } from './routes/dashboard.architecture'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard.announcements'
import { Route as DashboardAgendaFormateurRouteImport } from './routes/dashboard.agenda-formateur'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard.agenda'
import { Route as DashboardAccountingRouteImport } from './routes/dashboard.accounting'
import { Route as ApplyAdIdRouteImport } from './routes/apply.$adId'
import { Route as DashboardStudentsStudentIdRouteImport } from './routes/dashboard.students_.$studentId'
import { Route as DashboardSessionFeedbackSessionIdRouteImport } from './routes/dashboard.session-feedback.$sessionId'
import { Route as DashboardExamsNewRouteImport } from './routes/dashboard.exams_.new'
import { Route as DashboardCoursesCourseIdRouteImport } from './routes/dashboard.courses_.$courseId'
import { Route as DashboardRhEmployeesEmployeeIdRouteImport } from './routes/dashboard.rh_.employees_.$employeeId'
import { Route as DashboardExamsExamIdEditorRouteImport } from './routes/dashboard.exams_.$examId_.editor'
import { Route as DashboardCoursesCourseIdEditorModuleIdRouteImport } from './routes/dashboard.courses_.$courseId_.editor.$moduleId'

const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateformeRoute = PlateformeRouteImport.update({
  id: '/plateforme',
  path: '/plateforme',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproveLoginRoute = ApproveLoginRouteImport.update({
  id: '/approve-login',
  path: '/approve-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimetablesRoute = DashboardTimetablesRouteImport.update({
  id: '/timetables',
  path: '/timetables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeachingSessionsRoute =
  DashboardTeachingSessionsRouteImport.update({
    id: '/teaching-sessions',
    path: '/teaching-sessions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchedulesRoute = DashboardSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRhRoute = DashboardRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReunionsInstancesRoute =
  DashboardReunionsInstancesRouteImport.update({
    id: '/reunions-instances',
    path: '/reunions-instances',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPurchaseRequestsRoute =
  DashboardPurchaseRequestsRouteImport.update({
    id: '/purchase-requests',
    path: '/purchase-requests',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMeetingsRoute = DashboardMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamsRoute = DashboardExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunicationRoute = DashboardCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassesRoute = DashboardClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArchitectureRoute = DashboardArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaFormateurRoute =
  DashboardAgendaFormateurRouteImport.update({
    id: '/agenda-formateur',
    path: '/agenda-formateur',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountingRoute = DashboardAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => DashboardRoute,
} as any)
const ApplyAdIdRoute = ApplyAdIdRouteImport.update({
  id: '/apply/$adId',
  path: '/apply/$adId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentsStudentIdRoute =
  DashboardStudentsStudentIdRouteImport.update({
    id: '/students_/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSessionFeedbackSessionIdRoute =
  DashboardSessionFeedbackSessionIdRouteImport.update({
    id: '/session-feedback/$sessionId',
    path: '/session-feedback/$sessionId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardExamsNewRoute = DashboardExamsNewRouteImport.update({
  id: '/exams_/new',
  path: '/exams/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesCourseIdRoute =
  DashboardCoursesCourseIdRouteImport.update({
    id: '/courses_/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardRhEmployeesEmployeeIdRoute =
  DashboardRhEmployeesEmployeeIdRouteImport.update({
    id: '/rh_/employees_/$employeeId',
    path: '/rh/employees/$employeeId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardExamsExamIdEditorRoute =
  DashboardExamsExamIdEditorRouteImport.update({
    id: '/exams_/$examId_/editor',
    path: '/exams/$examId/editor',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCoursesCourseIdEditorModuleIdRoute =
  DashboardCoursesCourseIdEditorModuleIdRouteImport.update({
    id: '/courses_/$courseId_/editor/$moduleId',
    path: '/courses/$courseId/editor/$moduleId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/approve-login': typeof ApproveLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/formations': typeof FormationsRoute
  '/plateforme': typeof PlateformeRoute
  '/temoignages': typeof TemoignagesRoute
  '/apply/$adId': typeof ApplyAdIdRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/agenda-formateur': typeof DashboardAgendaFormateurRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/architecture': typeof DashboardArchitectureRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/communication': typeof DashboardCommunicationRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/purchase-requests': typeof DashboardPurchaseRequestsRoute
  '/dashboard/reunions-instances': typeof DashboardReunionsInstancesRoute
  '/dashboard/rh': typeof DashboardRhRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/teaching-sessions': typeof DashboardTeachingSessionsRoute
  '/dashboard/timetables': typeof DashboardTimetablesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRoute
  '/dashboard/exams/new': typeof DashboardExamsNewRoute
  '/dashboard/session-feedback/$sessionId': typeof DashboardSessionFeedbackSessionIdRoute
  '/dashboard/students/$studentId': typeof DashboardStudentsStudentIdRoute
  '/dashboard/exams/$examId/editor': typeof DashboardExamsExamIdEditorRoute
  '/dashboard/rh/employees/$employeeId': typeof DashboardRhEmployeesEmployeeIdRoute
  '/dashboard/courses/$courseId/editor/$moduleId': typeof DashboardCoursesCourseIdEditorModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/approve-login': typeof ApproveLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/plateforme': typeof PlateformeRoute
  '/temoignages': typeof TemoignagesRoute
  '/apply/$adId': typeof ApplyAdIdRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/agenda-formateur': typeof DashboardAgendaFormateurRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/architecture': typeof DashboardArchitectureRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/communication': typeof DashboardCommunicationRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/purchase-requests': typeof DashboardPurchaseRequestsRoute
  '/dashboard/reunions-instances': typeof DashboardReunionsInstancesRoute
  '/dashboard/rh': typeof DashboardRhRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/teaching-sessions': typeof DashboardTeachingSessionsRoute
  '/dashboard/timetables': typeof DashboardTimetablesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/courses/$courseId': typeof DashboardCoursesCourseIdRoute
  '/dashboard/exams/new': typeof DashboardExamsNewRoute
  '/dashboard/session-feedback/$sessionId': typeof DashboardSessionFeedbackSessionIdRoute
  '/dashboard/students/$studentId': typeof DashboardStudentsStudentIdRoute
  '/dashboard/exams/$examId/editor': typeof DashboardExamsExamIdEditorRoute
  '/dashboard/rh/employees/$employeeId': typeof DashboardRhEmployeesEmployeeIdRoute
  '/dashboard/courses/$courseId/editor/$moduleId': typeof DashboardCoursesCourseIdEditorModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/approve-login': typeof ApproveLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/formations': typeof FormationsRoute
  '/plateforme': typeof PlateformeRoute
  '/temoignages': typeof TemoignagesRoute
  '/apply/$adId': typeof ApplyAdIdRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/agenda-formateur': typeof DashboardAgendaFormateurRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/architecture': typeof DashboardArchitectureRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/communication': typeof DashboardCommunicationRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/purchase-requests': typeof DashboardPurchaseRequestsRoute
  '/dashboard/reunions-instances': typeof DashboardReunionsInstancesRoute
  '/dashboard/rh': typeof DashboardRhRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/teaching-sessions': typeof DashboardTeachingSessionsRoute
  '/dashboard/timetables': typeof DashboardTimetablesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/courses_/$courseId': typeof DashboardCoursesCourseIdRoute
  '/dashboard/exams_/new': typeof DashboardExamsNewRoute
  '/dashboard/session-feedback/$sessionId': typeof DashboardSessionFeedbackSessionIdRoute
  '/dashboard/students_/$studentId': typeof DashboardStudentsStudentIdRoute
  '/dashboard/exams_/$examId_/editor': typeof DashboardExamsExamIdEditorRoute
  '/dashboard/rh_/employees_/$employeeId': typeof DashboardRhEmployeesEmployeeIdRoute
  '/dashboard/courses_/$courseId_/editor/$moduleId': typeof DashboardCoursesCourseIdEditorModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/approve-login'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/formations'
    | '/plateforme'
    | '/temoignages'
    | '/apply/$adId'
    | '/dashboard/accounting'
    | '/dashboard/agenda'
    | '/dashboard/agenda-formateur'
    | '/dashboard/announcements'
    | '/dashboard/architecture'
    | '/dashboard/assignments'
    | '/dashboard/classes'
    | '/dashboard/communication'
    | '/dashboard/courses'
    | '/dashboard/documents'
    | '/dashboard/exams'
    | '/dashboard/library'
    | '/dashboard/meetings'
    | '/dashboard/notifications'
    | '/dashboard/performance'
    | '/dashboard/profile'
    | '/dashboard/purchase-requests'
    | '/dashboard/reunions-instances'
    | '/dashboard/rh'
    | '/dashboard/schedules'
    | '/dashboard/students'
    | '/dashboard/tasks'
    | '/dashboard/teaching-sessions'
    | '/dashboard/timetables'
    | '/dashboard/users'
    | '/verify/$code'
    | '/dashboard/'
    | '/dashboard/courses/$courseId'
    | '/dashboard/exams/new'
    | '/dashboard/session-feedback/$sessionId'
    | '/dashboard/students/$studentId'
    | '/dashboard/exams/$examId/editor'
    | '/dashboard/rh/employees/$employeeId'
    | '/dashboard/courses/$courseId/editor/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/approve-login'
    | '/auth'
    | '/contact'
    | '/formations'
    | '/plateforme'
    | '/temoignages'
    | '/apply/$adId'
    | '/dashboard/accounting'
    | '/dashboard/agenda'
    | '/dashboard/agenda-formateur'
    | '/dashboard/announcements'
    | '/dashboard/architecture'
    | '/dashboard/assignments'
    | '/dashboard/classes'
    | '/dashboard/communication'
    | '/dashboard/courses'
    | '/dashboard/documents'
    | '/dashboard/exams'
    | '/dashboard/library'
    | '/dashboard/meetings'
    | '/dashboard/notifications'
    | '/dashboard/performance'
    | '/dashboard/profile'
    | '/dashboard/purchase-requests'
    | '/dashboard/reunions-instances'
    | '/dashboard/rh'
    | '/dashboard/schedules'
    | '/dashboard/students'
    | '/dashboard/tasks'
    | '/dashboard/teaching-sessions'
    | '/dashboard/timetables'
    | '/dashboard/users'
    | '/verify/$code'
    | '/dashboard'
    | '/dashboard/courses/$courseId'
    | '/dashboard/exams/new'
    | '/dashboard/session-feedback/$sessionId'
    | '/dashboard/students/$studentId'
    | '/dashboard/exams/$examId/editor'
    | '/dashboard/rh/employees/$employeeId'
    | '/dashboard/courses/$courseId/editor/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/approve-login'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/formations'
    | '/plateforme'
    | '/temoignages'
    | '/apply/$adId'
    | '/dashboard/accounting'
    | '/dashboard/agenda'
    | '/dashboard/agenda-formateur'
    | '/dashboard/announcements'
    | '/dashboard/architecture'
    | '/dashboard/assignments'
    | '/dashboard/classes'
    | '/dashboard/communication'
    | '/dashboard/courses'
    | '/dashboard/documents'
    | '/dashboard/exams'
    | '/dashboard/library'
    | '/dashboard/meetings'
    | '/dashboard/notifications'
    | '/dashboard/performance'
    | '/dashboard/profile'
    | '/dashboard/purchase-requests'
    | '/dashboard/reunions-instances'
    | '/dashboard/rh'
    | '/dashboard/schedules'
    | '/dashboard/students'
    | '/dashboard/tasks'
    | '/dashboard/teaching-sessions'
    | '/dashboard/timetables'
    | '/dashboard/users'
    | '/verify/$code'
    | '/dashboard/'
    | '/dashboard/courses_/$courseId'
    | '/dashboard/exams_/new'
    | '/dashboard/session-feedback/$sessionId'
    | '/dashboard/students_/$studentId'
    | '/dashboard/exams_/$examId_/editor'
    | '/dashboard/rh_/employees_/$employeeId'
    | '/dashboard/courses_/$courseId_/editor/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRoute
  ApproveLoginRoute: typeof ApproveLoginRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FormationsRoute: typeof FormationsRoute
  PlateformeRoute: typeof PlateformeRoute
  TemoignagesRoute: typeof TemoignagesRoute
  ApplyAdIdRoute: typeof ApplyAdIdRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plateforme': {
      id: '/plateforme'
      path: '/plateforme'
      fullPath: '/plateforme'
      preLoaderRoute: typeof PlateformeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approve-login': {
      id: '/approve-login'
      path: '/approve-login'
      fullPath: '/approve-login'
      preLoaderRoute: typeof ApproveLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/timetables': {
      id: '/dashboard/timetables'
      path: '/timetables'
      fullPath: '/dashboard/timetables'
      preLoaderRoute: typeof DashboardTimetablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teaching-sessions': {
      id: '/dashboard/teaching-sessions'
      path: '/teaching-sessions'
      fullPath: '/dashboard/teaching-sessions'
      preLoaderRoute: typeof DashboardTeachingSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedules': {
      id: '/dashboard/schedules'
      path: '/schedules'
      fullPath: '/dashboard/schedules'
      preLoaderRoute: typeof DashboardSchedulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rh': {
      id: '/dashboard/rh'
      path: '/rh'
      fullPath: '/dashboard/rh'
      preLoaderRoute: typeof DashboardRhRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reunions-instances': {
      id: '/dashboard/reunions-instances'
      path: '/reunions-instances'
      fullPath: '/dashboard/reunions-instances'
      preLoaderRoute: typeof DashboardReunionsInstancesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/purchase-requests': {
      id: '/dashboard/purchase-requests'
      path: '/purchase-requests'
      fullPath: '/dashboard/purchase-requests'
      preLoaderRoute: typeof DashboardPurchaseRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/meetings': {
      id: '/dashboard/meetings'
      path: '/meetings'
      fullPath: '/dashboard/meetings'
      preLoaderRoute: typeof DashboardMeetingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exams': {
      id: '/dashboard/exams'
      path: '/exams'
      fullPath: '/dashboard/exams'
      preLoaderRoute: typeof DashboardExamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/communication': {
      id: '/dashboard/communication'
      path: '/communication'
      fullPath: '/dashboard/communication'
      preLoaderRoute: typeof DashboardCommunicationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classes': {
      id: '/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof DashboardClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/architecture': {
      id: '/dashboard/architecture'
      path: '/architecture'
      fullPath: '/dashboard/architecture'
      preLoaderRoute: typeof DashboardArchitectureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda-formateur': {
      id: '/dashboard/agenda-formateur'
      path: '/agenda-formateur'
      fullPath: '/dashboard/agenda-formateur'
      preLoaderRoute: typeof DashboardAgendaFormateurRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting': {
      id: '/dashboard/accounting'
      path: '/accounting'
      fullPath: '/dashboard/accounting'
      preLoaderRoute: typeof DashboardAccountingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/apply/$adId': {
      id: '/apply/$adId'
      path: '/apply/$adId'
      fullPath: '/apply/$adId'
      preLoaderRoute: typeof ApplyAdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/students_/$studentId': {
      id: '/dashboard/students_/$studentId'
      path: '/students/$studentId'
      fullPath: '/dashboard/students/$studentId'
      preLoaderRoute: typeof DashboardStudentsStudentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/session-feedback/$sessionId': {
      id: '/dashboard/session-feedback/$sessionId'
      path: '/session-feedback/$sessionId'
      fullPath: '/dashboard/session-feedback/$sessionId'
      preLoaderRoute: typeof DashboardSessionFeedbackSessionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exams_/new': {
      id: '/dashboard/exams_/new'
      path: '/exams/new'
      fullPath: '/dashboard/exams/new'
      preLoaderRoute: typeof DashboardExamsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses_/$courseId': {
      id: '/dashboard/courses_/$courseId'
      path: '/courses/$courseId'
      fullPath: '/dashboard/courses/$courseId'
      preLoaderRoute: typeof DashboardCoursesCourseIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rh_/employees_/$employeeId': {
      id: '/dashboard/rh_/employees_/$employeeId'
      path: '/rh/employees/$employeeId'
      fullPath: '/dashboard/rh/employees/$employeeId'
      preLoaderRoute: typeof DashboardRhEmployeesEmployeeIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exams_/$examId_/editor': {
      id: '/dashboard/exams_/$examId_/editor'
      path: '/exams/$examId/editor'
      fullPath: '/dashboard/exams/$examId/editor'
      preLoaderRoute: typeof DashboardExamsExamIdEditorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses_/$courseId_/editor/$moduleId': {
      id: '/dashboard/courses_/$courseId_/editor/$moduleId'
      path: '/courses/$courseId/editor/$moduleId'
      fullPath: '/dashboard/courses/$courseId/editor/$moduleId'
      preLoaderRoute: typeof DashboardCoursesCourseIdEditorModuleIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountingRoute: typeof DashboardAccountingRoute
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardAgendaFormateurRoute: typeof DashboardAgendaFormateurRoute
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardArchitectureRoute: typeof DashboardArchitectureRoute
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardClassesRoute: typeof DashboardClassesRoute
  DashboardCommunicationRoute: typeof DashboardCommunicationRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardExamsRoute: typeof DashboardExamsRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardMeetingsRoute: typeof DashboardMeetingsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardPurchaseRequestsRoute: typeof DashboardPurchaseRequestsRoute
  DashboardReunionsInstancesRoute: typeof DashboardReunionsInstancesRoute
  DashboardRhRoute: typeof DashboardRhRoute
  DashboardSchedulesRoute: typeof DashboardSchedulesRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardTeachingSessionsRoute: typeof DashboardTeachingSessionsRoute
  DashboardTimetablesRoute: typeof DashboardTimetablesRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCoursesCourseIdRoute: typeof DashboardCoursesCourseIdRoute
  DashboardExamsNewRoute: typeof DashboardExamsNewRoute
  DashboardSessionFeedbackSessionIdRoute: typeof DashboardSessionFeedbackSessionIdRoute
  DashboardStudentsStudentIdRoute: typeof DashboardStudentsStudentIdRoute
  DashboardExamsExamIdEditorRoute: typeof DashboardExamsExamIdEditorRoute
  DashboardRhEmployeesEmployeeIdRoute: typeof DashboardRhEmployeesEmployeeIdRoute
  DashboardCoursesCourseIdEditorModuleIdRoute: typeof DashboardCoursesCourseIdEditorModuleIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountingRoute: DashboardAccountingRoute,
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardAgendaFormateurRoute: DashboardAgendaFormateurRoute,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardArchitectureRoute: DashboardArchitectureRoute,
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardClassesRoute: DashboardClassesRoute,
  DashboardCommunicationRoute: DashboardCommunicationRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardExamsRoute: DashboardExamsRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardMeetingsRoute: DashboardMeetingsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardPurchaseRequestsRoute: DashboardPurchaseRequestsRoute,
  DashboardReunionsInstancesRoute: DashboardReunionsInstancesRoute,
  DashboardRhRoute: DashboardRhRoute,
  DashboardSchedulesRoute: DashboardSchedulesRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardTeachingSessionsRoute: DashboardTeachingSessionsRoute,
  DashboardTimetablesRoute: DashboardTimetablesRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCoursesCourseIdRoute: DashboardCoursesCourseIdRoute,
  DashboardExamsNewRoute: DashboardExamsNewRoute,
  DashboardSessionFeedbackSessionIdRoute:
    DashboardSessionFeedbackSessionIdRoute,
  DashboardStudentsStudentIdRoute: DashboardStudentsStudentIdRoute,
  DashboardExamsExamIdEditorRoute: DashboardExamsExamIdEditorRoute,
  DashboardRhEmployeesEmployeeIdRoute: DashboardRhEmployeesEmployeeIdRoute,
  DashboardCoursesCourseIdEditorModuleIdRoute:
    DashboardCoursesCourseIdEditorModuleIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRoute,
  ApproveLoginRoute: ApproveLoginRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FormationsRoute: FormationsRoute,
  PlateformeRoute: PlateformeRoute,
  TemoignagesRoute: TemoignagesRoute,
  ApplyAdIdRoute: ApplyAdIdRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
