/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as PlateformeRouteImport } from './routes/plateforme'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardSchedulesRouteImport } from './routes/dashboard.schedules'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMeetingsRouteImport } from './routes/dashboard.meetings'
import { Route as DashboardExamsRouteImport } from './routes/dashboard.exams'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardClassesRouteImport } from './routes/dashboard.classes'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard.assignments'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard.announcements'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard.agenda'
import { Route as DashboardAccountingRouteImport } from './routes/dashboard.accounting'

const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateformeRoute = PlateformeRouteImport.update({
  id: '/plateforme',
  path: '/plateforme',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchedulesRoute = DashboardSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMeetingsRoute = DashboardMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExamsRoute = DashboardExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClassesRoute = DashboardClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountingRoute = DashboardAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/formations': typeof FormationsRoute
  '/plateforme': typeof PlateformeRoute
  '/temoignages': typeof TemoignagesRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/plateforme': typeof PlateformeRoute
  '/temoignages': typeof TemoignagesRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/formations': typeof FormationsRoute
  '/plateforme': typeof PlateformeRoute
  '/temoignages': typeof TemoignagesRoute
  '/dashboard/accounting': typeof DashboardAccountingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/classes': typeof DashboardClassesRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/exams': typeof DashboardExamsRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/schedules': typeof DashboardSchedulesRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/formations'
    | '/plateforme'
    | '/temoignages'
    | '/dashboard/accounting'
    | '/dashboard/agenda'
    | '/dashboard/announcements'
    | '/dashboard/assignments'
    | '/dashboard/classes'
    | '/dashboard/courses'
    | '/dashboard/documents'
    | '/dashboard/exams'
    | '/dashboard/meetings'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/schedules'
    | '/dashboard/students'
    | '/dashboard/users'
    | '/verify/$code'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/auth'
    | '/contact'
    | '/formations'
    | '/plateforme'
    | '/temoignages'
    | '/dashboard/accounting'
    | '/dashboard/agenda'
    | '/dashboard/announcements'
    | '/dashboard/assignments'
    | '/dashboard/classes'
    | '/dashboard/courses'
    | '/dashboard/documents'
    | '/dashboard/exams'
    | '/dashboard/meetings'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/schedules'
    | '/dashboard/students'
    | '/dashboard/users'
    | '/verify/$code'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/formations'
    | '/plateforme'
    | '/temoignages'
    | '/dashboard/accounting'
    | '/dashboard/agenda'
    | '/dashboard/announcements'
    | '/dashboard/assignments'
    | '/dashboard/classes'
    | '/dashboard/courses'
    | '/dashboard/documents'
    | '/dashboard/exams'
    | '/dashboard/meetings'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/schedules'
    | '/dashboard/students'
    | '/dashboard/users'
    | '/verify/$code'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FormationsRoute: typeof FormationsRoute
  PlateformeRoute: typeof PlateformeRoute
  TemoignagesRoute: typeof TemoignagesRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plateforme': {
      id: '/plateforme'
      path: '/plateforme'
      fullPath: '/plateforme'
      preLoaderRoute: typeof PlateformeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedules': {
      id: '/dashboard/schedules'
      path: '/schedules'
      fullPath: '/dashboard/schedules'
      preLoaderRoute: typeof DashboardSchedulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/meetings': {
      id: '/dashboard/meetings'
      path: '/meetings'
      fullPath: '/dashboard/meetings'
      preLoaderRoute: typeof DashboardMeetingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/exams': {
      id: '/dashboard/exams'
      path: '/exams'
      fullPath: '/dashboard/exams'
      preLoaderRoute: typeof DashboardExamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/classes': {
      id: '/dashboard/classes'
      path: '/classes'
      fullPath: '/dashboard/classes'
      preLoaderRoute: typeof DashboardClassesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounting': {
      id: '/dashboard/accounting'
      path: '/accounting'
      fullPath: '/dashboard/accounting'
      preLoaderRoute: typeof DashboardAccountingRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountingRoute: typeof DashboardAccountingRoute
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardClassesRoute: typeof DashboardClassesRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardExamsRoute: typeof DashboardExamsRoute
  DashboardMeetingsRoute: typeof DashboardMeetingsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSchedulesRoute: typeof DashboardSchedulesRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountingRoute: DashboardAccountingRoute,
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardClassesRoute: DashboardClassesRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardExamsRoute: DashboardExamsRoute,
  DashboardMeetingsRoute: DashboardMeetingsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSchedulesRoute: DashboardSchedulesRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FormationsRoute: FormationsRoute,
  PlateformeRoute: PlateformeRoute,
  TemoignagesRoute: TemoignagesRoute,
  VerifyCodeRoute: VerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
